oras-project/oras-java

.github/workflows/build.yml

Add PR build workflow

---

.github/workflows/deploy-snapshots.yml
README.md
pom.xml

GitHub snaphosts deploy

---

pom.xml
src/main/java/land/oras/Registry.java
src/test/java/land/oras/AnnotationsTest.java
src/test/java/land/oras/ContainerRefTest.java
src/test/java/land/oras/LayerTest.java
src/test/java/land/oras/ManifestTest.java
src/test/java/land/oras/RegistryContainerTest.java
src/test/java/land/oras/RegistryWireMockTest.java
src/test/java/land/oras/auth/BearerTokenProviderTest.java
src/test/java/land/oras/auth/EnvironmentPasswordProviderTest.java
src/test/java/land/oras/utils/DigestUtilsTest.java
src/test/resources/junit-platform.properties

Optimize tests duration by using Junit 5 concurrency
```[tasklist]
```

Optimize tests duration by using Junit 5 concurrency

---

.github/workflows/deploy-snapshots.yml

Sadly openssf doesn't detect such workflow as release workflow
Since it require 
```go
{
Uses: "actions/setup-java",
},
{
Run: "mvn.*deploy",
},
```
Not ideal but I least would increase the score

Use setup java action for package detection

---

src/main/java/land/oras/Config.java
src/main/java/land/oras/Layer.java
src/main/java/land/oras/Manifest.java
src/main/java/land/oras/Registry.java
src/main/java/land/oras/utils/Const.java
src/main/java/land/oras/utils/JsonUtils.java
src/test/java/land/oras/ConfigTest.java
src/test/java/land/oras/ManifestTest.java
src/test/java/land/oras/RegistryTest.java

Fix https://github.com/oras-project/oras-java/issues/141
Automated
Tested with ORAS and test java cli
CLI Go
```json
{
"annotations": {
"org.opencontainers.image.created": "2025-02-23T09:50:04Z"
},
"artifactType": "application/vnd.unknown.artifact.v1",
"config": {
"data": "e30=",
"digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
"mediaType": "application/vnd.oci.empty.v1+json",
"size": 2
},
"layers": [
{
"annotations": {
"org.opencontainers.image.title": "hello.txt"
},
"digest": "sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730",
"mediaType": "application/vnd.oci.image.layer.v1.tar",
"size": 4
}
],
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"schemaVersion": 2
}
```
Java
```json
{
"annotations": { …
```

Better OCI compatibility

---

src/main/java/land/oras/ContainerRef.java
src/main/java/land/oras/Layer.java
src/main/java/land/oras/Registry.java
src/main/java/land/oras/utils/DigestUtils.java
src/main/java/land/oras/utils/SupportedAlgorithm.java
src/test/java/land/oras/ContainerRefTest.java
src/test/java/land/oras/RegistryTest.java
src/test/java/land/oras/utils/DigestUtilsTest.java

Default is still SHA-256 but do not fail when SHA-512 is used
Default is still SHA-256 but do not fail when SHA-512 is used
CI

Add support for SHA-512 hash

---

pom.xml
src/main/java/land/oras/LocalPath.java
src/main/java/land/oras/Registry.java
src/main/java/land/oras/utils/ArchiveUtils.java
src/main/java/land/oras/utils/Const.java
src/test/java/land/oras/RegistryTest.java
src/test/java/land/oras/utils/ArchiveUtilsTest.java

Fix https://github.com/oras-project/oras-java/issues/154
Add support for zstd compression/uncompression
CI only

Add suport for `application/vnd.oci.image.layer.v1.tar+zstd` compression

---

src/main/java/land/oras/Registry.java
src/test/java/land/oras/RegistryTest.java

Fix https://github.com/oras-project/oras-java/issues/164
CI

Add support for attach utility

---

src/main/java/land/oras/utils/ArchiveUtils.java
src/main/java/land/oras/utils/DigestUtils.java
src/main/java/land/oras/utils/SupportedAlgorithm.java
src/main/java/land/oras/utils/SupportedCompression.java
src/test/java/land/oras/RegistryTest.java

Support for no compression for directories

---

src/main/java/land/oras/ArtifactType.java
src/main/java/land/oras/ContainerRef.java
src/main/java/land/oras/Manifest.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/ArtifactTypeTest.java
src/test/java/land/oras/ManifestTest.java
src/test/java/land/oras/RegistryTest.java

Validation of artifactType

---

src/main/java/land/oras/ContainerRef.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/ContainerRefTest.java
src/test/java/land/oras/RegistryWireMockTest.java

Should fix https://github.com/oras-project/oras-java/issues/177
Similar to https://github.com/oras-project/oras-py/blob/1790ad7df3c83884f24aabd2ab4b2d97e4c2f3b0/oras/defaults.py#L10-L15 and https://github.com/oras-project/oras-go/blob/d92df9df65805259b6f3b8114d9dc939d71f5264/registry/reference_test.go#L235-L249
CI only

Replace docker.io by registry-1.docker.io when doing api calls

---

src/main/java/land/oras/Registry.java
src/main/java/land/oras/auth/BearerTokenProvider.java
src/test/java/land/oras/RegistryTest.java

Should fix https://github.com/oras-project/oras-java/issues/178
CI and enable test that was ignored

Support anonymous request token auth for GHCR

---

src/main/java/land/oras/Annotations.java
src/main/java/land/oras/ContainerRef.java
src/main/java/land/oras/Manifest.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/AnnotationsTest.java
src/test/java/land/oras/ContainerRefTest.java
src/test/java/land/oras/ManifestTest.java

Use library namespace by default for docker.io images
Also found during interactive tests that multi-arch images are not exported (since an index is returned). An other PR will follow
CI and interactive tests with docker.io

Use library namespace by default for docker.io images

---

README.md
pom.xml

- Release workflow is ready to be used (artifacts signed, plugin added etc...)
- I think publishing to "land.oras" is enough. Since the artifact id is already `oras-java-sdk`
- This should finalize the maven central publication. The last step is the domain verification
- I would like also oras owner have access to this namespace
- This require domain validation via DNS https://central.sonatype.org/register/namespace/#for-dns Basically a domain admin must registrer a TXT record. Then we can hit "Verify" domain
[tasklist]

Match group id for domain www.oras.land

---

README.md

Add reproducible build badge
None

Add reproducible build badge and update examples

---

src/main/java/land/oras/Index.java
src/main/java/land/oras/Manifest.java
src/main/java/land/oras/Registry.java
src/main/java/land/oras/utils/Const.java
src/test/java/land/oras/RegistryTest.java

Save descriptor as-is on OCI layout
Save descriptor as-is on OCI layout
CI

Save descriptor as-is on OCI layout

---

src/main/java/land/oras/Registry.java
src/main/java/land/oras/utils/Const.java
src/test/java/land/oras/RegistryWireMockTest.java

Would fix: https://github.com/oras-project/oras-java/issues/194
CI and some OCI layout export from a legacy docker layout

Add support for docker content types

---

src/main/java/land/oras/Registry.java
src/main/java/land/oras/auth/BearerTokenProvider.java
src/test/java/land/oras/RegistryWireMockTest.java
src/test/java/land/oras/auth/BearerTokenProviderTest.java

Reuse current HTTP client when refresh the token
CI

Reuse current HTTP client when refresh the token

---

src/main/java/land/oras/Config.java
src/main/java/land/oras/Descriptor.java
src/main/java/land/oras/Layer.java
src/main/java/land/oras/Manifest.java
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/Referrers.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/ConfigTest.java
src/test/java/land/oras/OCILayoutTest.java
src/test/java/land/oras/RegistryTest.java

Add descriptor class and recursirve OCI layout copy
CI

Add descriptor class and recursirve OCI layout copy

---

src/main/java/land/oras/ContainerRef.java
src/main/java/land/oras/LayoutRef.java
src/main/java/land/oras/OCI.java
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/Ref.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/LayoutRefTest.java
src/test/java/land/oras/OCILayoutTest.java

Push blob to OCI layout

---

pom.xml
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/OCILayoutTest.java
src/test/java/land/oras/RegistryTest.java
src/test/java/land/oras/RegistryWireMockTest.java

Validate digest when pushing blobs
CI

Validate digest when pushing blobs

---

src/main/java/land/oras/Config.java
src/main/java/land/oras/Descriptor.java
src/main/java/land/oras/Index.java
src/main/java/land/oras/Layer.java
src/main/java/land/oras/Manifest.java
src/test/java/land/oras/ConfigTest.java
src/test/java/land/oras/IndexTest.java
src/test/java/land/oras/ManifestDescriptorTest.java
src/test/java/land/oras/OCILayoutTest.java

Push up size, digest and artifact type on descriptor
CI

Push up size, digest and artifact type on descriptor

---

src/main/java/land/oras/utils/DigestUtils.java

Use FileChannel.map for efficient file reading to compute digest, leveraging memory-mapped I/O for better performance.
CI

Use FileChannel.map for efficient digest computation

---

src/main/java/land/oras/Annotations.java
src/main/java/land/oras/Index.java
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/utils/Const.java
src/main/java/land/oras/utils/JsonUtils.java
src/test/java/land/oras/IndexTest.java
src/test/java/land/oras/OCILayoutTest.java

Small issue I discovered comparing the java and go implementation
Test were indeed wrong
Manifest annotations where not copied to index
And added some cleanup

Manifest annotations where not copied to index

---

pom.xml
src/main/java/land/oras/utils/Const.java
src/main/java/land/oras/utils/OrasHttpClient.java
src/main/resources/version.properties

Add user agent header
CI and ensure by checking debug mode the header is sent
``` 
Headers: ****, User-Agent=[ORAS-Java-SDK/0.2.2-SNAPSHOT]} 
```

Add user agent header

---

src/main/java/land/oras/utils/Const.java
src/main/java/land/oras/utils/OrasHttpClient.java
src/test/java/land/oras/RegistryWireMockTest.java

Signed-off-by: Vaidik Bhardwaj <vaidikbhardwaj00@gmail.com>
- Added patch in `OrasHttpClient`
- Added range headers in `Const.java`
- As there are no dedicated test files for these two classes I just added a test for verifying a patch with newly added headers in the `WireMock` Test as it already contains tests for verifying headers and requests.
All new tests pass

add patch along with range headers for pushChunks

---

src/main/java/land/oras/LayoutRef.java
src/main/java/land/oras/OCI.java
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/LayoutRefTest.java
src/test/java/land/oras/OCILayoutTest.java

Push up pushIndex and prepare for reusable copy methods

Push up pushIndex and prepare for reusable copy methods

---

src/main/java/land/oras/Describable.java
src/main/java/land/oras/Index.java
src/main/java/land/oras/LayoutRef.java
src/main/java/land/oras/Manifest.java
src/main/java/land/oras/OCILayout.java
src/test/java/land/oras/LayoutRefTest.java
src/test/java/land/oras/OCILayoutTest.java

Reduce some code duplicate with Describable interface

Reduce some code duplicate with Describable interface

---

src/main/java/land/oras/CopyUtils.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/RegistryTest.java

And restore/add tests for registry copy
Ensure to push blobs and config before manifests

Ensure to push blobs and config before manifests

---

src/main/java/land/oras/CopyUtils.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/RegistryTest.java

Should fix https://github.com/oras-project/oras-java/issues/251
Branch was not tested
See https://github.com/oras-project/oras-java/issues/251

Fix overwrite for pullArtifact

---

src/main/java/land/oras/auth/AuthStore.java
src/test/java/land/oras/auth/AuthStoreTest.java

Do not fail if XDG_RUNTIME_DIR is not set
Fix https://github.com/oras-project/oras-java/issues/250
Also added a bit more tests that should help supporting better podman config to select correct credentials https://github.com/oras-project/oras-go/issues/918 and [containers-registries.conf](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md) based Container Registry alias etc....
mvn clean install and add/update tests

Do not fail if XDG_RUNTIME_DIR is not set

---

src/main/java/land/oras/OCI.java
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/Registry.java
src/test/java/land/oras/OCILayoutTest.java
src/test/java/land/oras/RegistryWireMockTest.java

Support for getting tags on OCI layout
Also breaking to return Tags object instead of a list of strings
mvn clean install and one automated tests

Support for getting tags on OCI layout

---

src/main/java/land/oras/LayoutRef.java
src/main/java/land/oras/OCI.java
src/test/java/land/oras/LayoutRefTest.java

Allow to copy layout from from OCI layout

Allow to copy layout from from OCI layout

---

src/main/java/land/oras/Registry.java
src/main/java/land/oras/auth/AbstractUsernamePasswordProvider.java
src/main/java/land/oras/auth/AuthScheme.java
src/main/java/land/oras/auth/AuthStoreAuthenticationProvider.java
src/main/java/land/oras/auth/BearerTokenProvider.java
src/main/java/land/oras/auth/NoAuthProvider.java
src/main/java/land/oras/exception/OrasException.java
src/main/java/land/oras/utils/HttpClient.java
src/test/java/land/oras/RegistryWireMockTest.java
src/test/java/land/oras/auth/BearerTokenProviderTest.java
src/test/java/land/oras/exception/OrasExceptionTest.java

Pass each time auth provider and handle token refresh on client instead of registry
Partially fix https://github.com/oras-project/oras-java/issues/17 but without token caching
This is not performance since the token will be requested on each request. 
Just parking this PR here
mvn clean
Missing automated and interactive tests

Pass each time auth provider and handle token refresh on client instead of registry

---

src/main/java/land/oras/utils/Const.java
src/test/java/land/oras/utils/ConstTest.java

Add two annotation constants

---

src/main/java/land/oras/utils/ArchiveUtils.java
src/test/java/land/oras/utils/ArchiveUtilsTest.java

Add some convenience methods on archive utils

Add some convenience methods on archive utils

---

src/main/java/land/oras/auth/HttpClient.java
src/test/java/land/oras/DockerIoITCase.java
src/test/java/land/oras/GitHubContainerRegistryITCase.java
src/test/java/land/oras/JFrogArtifactoryITCase.java
src/test/java/land/oras/RegistryWireMockTest.java

Probably regression of https://github.com/oras-project/oras-java/pull/273/files
Redirect was not done after redoing the request after getting auth token
Added one Wiremock and one Docker.io test

Missing redirect after getting auth token

---

src/main/java/land/oras/LayoutRef.java
src/main/java/land/oras/OCILayout.java
src/main/java/land/oras/Registry.java
src/main/java/land/oras/utils/SupportedAlgorithm.java
src/test/java/land/oras/DockerIoITCase.java
src/test/java/land/oras/GitHubContainerRegistryITCase.java
src/test/java/land/oras/JFrogArtifactoryITCase.java
src/test/java/land/oras/LayoutRefTest.java
src/test/java/land/oras/RegistryWireMockTest.java
src/test/java/land/oras/utils/SupportedAlgorithmTest.java

Validate `Docker-Content-Digest` when downloading or getting blob

Partial validate of `Docker-Content-Digest` when downloading or getting blob

---

src/main/java/land/oras/auth/HttpClient.java

When using basic authentication (username & password) to get a token via the `WWW-Authenticate` mechanism, the newly aquired token is added as an `Authorization` header on the request, resulting in two `Authorization` headers: one containing the username/password (`Authorization: Basic ...`) and one containing the token (`Authorization: Bearer ...`).
Some servers will reject a request with multiple `Authorization` headers.
These changes modify the behaviour so that, instead of adding an additional header, the bearer token replaces the username/password `Authorization` header.
I checked that only a single `Authorization` header (containing the token) is sent on requests after using basic authentication to acquire a token. The requests were able to successfully authenticate with a server …

Only send a single 'Authorization' header after getting a token

---

.github/workflows/updatecli.yaml
updatecli/updatecli.d/maven.yaml
updatecli/values.github-action.yaml

Updatecli configuration
In order to bump maven version on all files
```
updatecli diff --values updatecli/values.github-action.yaml -c updatecli/updatecli.d/maven.yaml
```

Updatecli configuration

---

.github/workflows/updatecli.yaml

Fix typo on updatecli permissions
None

Fix typo on updatecli permissions

---

src/main/java/land/oras/auth/HttpClient.java
src/test/java/land/oras/AnnotationsTest.java
src/test/java/land/oras/ArtifactTypeTest.java
src/test/java/land/oras/ClassAnnotationsTest.java
src/test/java/land/oras/ConfigTest.java
src/test/java/land/oras/DockerIoITCase.java
src/test/java/land/oras/GitHubContainerRegistryITCase.java
src/test/java/land/oras/HarborS3ITCase.java
src/test/java/land/oras/IndexTest.java
src/test/java/land/oras/JFrogArtifactoryITCase.java
src/test/java/land/oras/LayerTest.java
src/test/java/land/oras/LayoutRefTest.java
src/test/java/land/oras/LocalPathTest.java
src/test/java/land/oras/ManifestDescriptorTest.java
src/test/java/land/oras/ManifestTest.java
src/test/java/land/oras/OCILayoutTest.java
src/test/java/land/oras/QuayIoITCase.java
src/test/java/land/oras/RegistryTest.java
src/test/java/land/oras/RegistryWireMockTest.java
src/test/java/land/oras/SubjectTest.java
src/test/java/land/oras/auth/BearerTokenProviderTest.java
src/test/java/land/oras/auth/HttpClientTest.java
src/test/java/land/oras/auth/NoAuthProviderTest.java
src/test/java/land/oras/auth/ScopeUtilsTest.java
src/test/java/land/oras/auth/ScopesTest.java
src/test/java/land/oras/auth/UsernamePasswordProviderTest.java
src/test/java/land/oras/exception/OrasExceptionTest.java

Do not send credentials to other demain. Also now S3 reject Authorization header when signature is passed throught URL
```xml
<Error>
<Code>InvalidArgument</Code>
<Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message>
</Error>
```

Do not include auth header when redirecting to other domain or when switching to insecure protocol

---

src/main/java/land/oras/Registry.java
src/test/java/land/oras/HarborS3ITCase.java
src/test/java/land/oras/RegistryWireMockTest.java

Fix possible Nullpointer on digest validation

Fix possible Nullpointer on digest validation

---

updatecli/updatecli.d/maven.yaml
updatecli/updatecli.d/zot.yaml

Add updatecli manifest to update zot container for testcontainers
```
updatecli diff --values updatecli/values.github-action.yaml -c updatecli/updatecli.d/zot.yaml
```

Add updatecli manifest to update zot container for testcontainers

---

src/main/java/land/oras/OCI.java
src/main/java/land/oras/utils/ArchiveUtils.java
src/test/java/land/oras/RegistryTest.java
src/test/java/land/oras/ZotLocalhostITCase.java
src/test/java/land/oras/utils/ArchiveUtilsTest.java

Also fix nested folder. Previously only the folder name was taken which was not consistent with Go SDK
For example pushing `src/main/java` correctly set the title to `src/main/java`
Absolute path are also kept with original behavior (folder name). Expect they are not correctly packaged
```json
"layers": [
{
"annotations": {
"io.deis.oras.content.digest": "sha256:13e37d5391939b4f2b1f43a2f0966ec2b02266555e0399d7dd40208a98bb987b",
"io.deis.oras.content.unpack": "true",
"org.opencontainers.image.title": "src/main/java"
},
"digest": "sha256:eddce30abed45c67998e27aeb250542576ecdf0e95afa9c843dbca3521bf22b0",
"mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
"size": 40871
}
],
```
And is correctly pullable with oras pull
```
oras pull localhost:5000/foo:java
✓ Pulled      src/main/java …
```

Ensure to include parent folder into archive

---

.github/workflows/deploy-javadoc.yml

Small typo. Fix maven maven on deploy-javadoc

Fix maven maven on deploy-javadoc
