- .github/CODEOWNERS
- .github/dependabot.yml
- pom.xml
Finalize transfer and fix URL in pom.xml for distribution on GH packages
> Finalize transfer and fix URL in pom.xml for distribution on GH packages

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
Added two new issue templates that would help the contributor to create issues in this project
Related #21 .
* No testing is required for these changes 
```[tasklist]
```
> chore: Add two issue template

- pom.xml
Fix https://github.com/oras-project/oras-java/issues/57
Spotless configuration was added but not enabled by default. The existing code was already formatted
```[tasklist]
```
> Enable spotless

- pom.xml
Fix spotless check during build
mvn clean install and ensure spotless rules are check during build
```[tasklist]
- x ] The description of this pull request is detailed and explain why this pull request is needed
```
> Fix spotless check during build

- README.md
Add installation about consuming the SDK on maven
None
[tasklist]
> Add SDK installation instruction

- .github/workflows/release-drafter.yml
Add release drafter workflow
```[tasklist]
```
> Add release drafter workflow

- .github/release-drafter.yml
Add release draft configuration
```[tasklist]
```
> Add release draft configuration

- .github/workflows/build.yml
- .github/workflows/deploy-javadoc.yml
- pom.xml
- src/main/java/land/oras/Annotations.java
Ensure valid Javadoc and publish it to GitHub pages
Should fix https://github.com/oras-project/oras-java/issues/22
[tasklist]
> Ensure valid Javadoc and publish it to GitHub pages

- .github/workflows/deploy-javadoc.yml
Duplicate id on workflow
Will do on main
> Duplicate id on workflow

- .github/workflows/deploy-javadoc.yml
Fix workflow permission
Fix workflow permission
Will test on main
> Fix workflow permission

- .github/workflows/deploy-javadoc.yml
Rename job name
Rename job name
Will test workflow on main
[tasklist]
> Rename job name

- README.md
Add link for Javadoc on readme
[tasklist]
> Add link for Javadoc on readme

- .github/workflows/release.yml
- pom.xml
Add missing scm and release plugin
> Add missing scm and release plugin

- .github/workflows/release.yml
- pom.xml
> Setup SSH key

- .github/workflows/release.yml
- .mvn/maven.config
- README.md
- pom.xml
> Fix version on pom.xml

- .github/workflows/deploy-snapshots.yml
- pom.xml
> Sign snaphosts

- .github/workflows/deploy-snapshots.yml
> Pass sign-only profile

- .github/workflows/deploy-snapshots.yml
- .github/workflows/release.yml
> Add central settings

- pom.xml
- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
- src/main/java/land/oras/credentials/FileStore.java
- src/test/java/land/oras/RegistryContainerTest.java
- src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
- src/test/java/land/oras/credentials/FileStoreTest.java
Fix docker auth and implement test for it
Implement one test for using docker auth
> Fix docker auth and implement test for it

- pom.xml
Restore 0.1.1-SNAPSHOT
Restore 0.1.1-SNAPSHOT
None
```
> Restore 0.1.1-SNAPSHOT

- pom.xml
> Revert release

- .github/workflows/release.yml
Write permission for content on release
None
> Write permission for content on release

- .github/workflows/deploy-snapshots.yml
- pom.xml
Add sigstore signature for snapshot and releases
```
mvn -Psign-only clean install
```
> Add sigstore signature for snapshot and releases

- .github/workflows/deploy-snapshots.yml
- .github/workflows/release.yml
> Fix id-token permission

- pom.xml
Reproducible builds
Reproducible builds
> Reproducible builds

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/auth/AbstractUsernamePasswordProvider.java
- src/main/java/land/oras/auth/AuthProvider.java
- src/main/java/land/oras/auth/BearerTokenProvider.java
- src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
- src/main/java/land/oras/auth/NoAuthProvider.java
- src/main/java/land/oras/utils/OrasHttpClient.java
- src/test/java/land/oras/ContainerRefTest.java
- src/test/java/land/oras/RegistryWireMockTest.java
- src/test/java/land/oras/auth/BearerTokenProviderTest.java
- src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
Allow file store provider to select credentials
and interactive test with ora cli java
> Allow file store provider to select credentials

- .github/workflows/scorecard.yml
> Add Security ossf scorecard

- .github/workflows/scorecard.yml
Fix missing v prefix on workflow tag
None
> Fix missing v prefix on workflow tag

- README.md
> Add some OSS badges

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/pull_request_template.md
- .github/workflows/build.yml
- .gitignore
- .pre-commit-config.yaml
Add precommit action to PR build
> Add precommit action to PR build

- .github/workflows/deploy-javadoc.yml
- .github/workflows/deploy-snapshots.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release.yml
Avoid permission at workflow level
> Avoid permission at workflow level

- .github/workflows/deploy-snapshots.yml
- README.md
> Add codecov on main branch

- .github/workflows/deploy-snapshots.yml
> Fix jacoco location

- pom.xml
Run jacoco on sign-only-profile
None
> Run jacoco on sign-only-profile

- .github/workflows/deploy-snapshots.yml
- pom.xml
Rename sign-only to sign-profile and don't skipTests by default
None
> Rename sign-only to sign-profile and don't skipTests by default

- .github/.codecov.yml
- README.md
> Add codecov config

- src/main/java/land/oras/utils/ArchiveUtils.java
- src/main/java/land/oras/utils/DigestUtils.java
- src/test/java/land/oras/utils/ArchiveUtilsTest.java
- src/test/java/land/oras/utils/DigestUtilsTest.java
Increase coverage for archive and digests
CI
> Increase coverage for archive and digests

- .github/.codecov.yml
- .github/workflows/build.yml
> Add codecov on PR build

- src/main/java/land/oras/utils/ArchiveUtils.java
- src/test/java/land/oras/auth/FileStoreAuthenticationProviderTest.java
- src/test/java/land/oras/auth/UsernamePasswordProviderTest.java
- src/test/java/land/oras/exception/ErrorTest.java
- src/test/java/land/oras/exception/OrasExceptionTest.java
- src/test/java/land/oras/utils/ArchiveUtilsTest.java
Fix few issue with `ArchiveUtils` (empty dir, symlink, permissions) and increase overall coverage
CI
> Fix few issue with `ArchiveUtils` (empty dir, symlink, permissions) and increase overall coverage

- .github/.codecov.yml
- src/main/java/land/oras/utils/JsonUtils.java
- src/test/java/land/oras/LayerTest.java
- src/test/java/land/oras/utils/JsonUtilsTest.java
> Increase to 80% coverage

- .github/workflows/release.yml
Update jar and signature to release
This should also increase the openssf score
None
> Update jar and signature to release

- .github/workflows/release.yml
Maven release sign commits
None
> Maven release sign commits

- .github/workflows/release.yml
Fetch again release_id and add logs and fix target/checkout/target directory
> Fetch again release_id and add logs

- README.md
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/auth/AbstractUsernamePasswordProvider.java
- src/main/java/land/oras/auth/BearerTokenProvider.java
- src/main/java/land/oras/auth/FileStoreAuthenticationProvider.java
- src/main/java/land/oras/auth/NoAuthProvider.java
- src/main/java/land/oras/auth/UsernamePasswordProvider.java
- src/test/java/land/oras/RegistryTest.java
Add common builder method defaults and insecure
CI
> Add common builder method defaults and insecure

- .github/workflows/release.yml
Artifacts are now also uploaded on GitHub release
None
> Artifacts are now also uploaded on GitHub release

- .github/workflows/build.yml
- .github/workflows/deploy-javadoc.yml
- .github/workflows/deploy-snapshots.yml
- .github/workflows/release-drafter.yml
- .github/workflows/scorecard.yml
Allow manual trigger of workflows
None
> Allow manual trigger of workflows

- .github/workflows/release.yml
Not needed
Skip sources and javadoc on release GitHub artifacts
> Skip sources and javadoc on release GitHub artifacts

- .github/pull_request_template.md
- src/CONTRIBUTING.md
> Add contributing guide

- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/utils/ArchiveUtils.java
- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/utils/ArchiveUtilsTest.java
Missing extraction on pullArtifact
Automated tests
Test to push an archive with oras go and pull it via java
> Missing extraction on pullArtifact

- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/RegistryTest.java
Simple implementation of copy
CI
> Simple implementation of copy

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/utils/ArchiveUtils.java
- src/main/java/land/oras/utils/Const.java
- src/main/java/land/oras/utils/SupportedAlgorithm.java
- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/utils/ArchiveUtilsTest.java
- src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Add support for io.deis.oras.content.digest annotation
CI only for now
> Add support for io.deis.oras.content.digest annotation

- src/main/java/land/oras/Config.java
- src/main/java/land/oras/Manifest.java
- src/main/java/land/oras/ManifestDescriptor.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/Subject.java
- src/main/java/land/oras/utils/Const.java
- src/test/java/land/oras/ManifestTest.java
- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/SubjectTest.java
Partial support for referals.
Support adding a `Subject` to an Artifact
Reference
https://oras.land/docs/concepts/reftypes/
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers
CI and interactive tests with ORAS and Java CLI
> Partial support for referals

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/ManifestDescriptor.java
- src/main/java/land/oras/Referrers.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/utils/Const.java
- src/test/java/land/oras/RegistryTest.java
Implement /referrers endpoint
Mostly CI
> Implement /referrers endpoint

- src/main/java/land/oras/LocalPath.java
- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/LocalPathTest.java
- src/test/java/land/oras/RegistryTest.java
> Allow setting media type

- .gitignore
- src/main/java/land/oras/Config.java
- src/main/java/land/oras/Index.java
- src/main/java/land/oras/OciLayout.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/utils/SupportedAlgorithm.java
- src/test/java/land/oras/IndexTest.java
- src/test/java/land/oras/RegistryTest.java
Need more tests and missing index for now
Need code cleanup and factorize
Export to OCI layout
CI
> Export to OCI layout

- src/main/java/land/oras/Index.java
- src/main/java/land/oras/ManifestDescriptor.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/utils/Const.java
- src/test/java/land/oras/IndexTest.java
- src/test/java/land/oras/ManifestDescriptorTest.java
- src/test/java/land/oras/RegistryTest.java
Support for platform fields and ensure all manifests are resolved when getting index
CI
java -jar java-oras-cli/target/oras-java.jar copy-oci library/alpine --output alpine --debug
> Support for platform fields and ensure all manifests are resolved when getting index

- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/utils/Const.java
- src/test/java/land/oras/OCILayoutTest.java
- src/test/java/land/oras/OCILayoutWireMockTest.java
> Cleanup OCI layout

- src/main/java/land/oras/OCILayout.java
- src/test/java/land/oras/OCILayoutTest.java
Create OCI layout and various OCILayoutTest cleanup
CI
> Create OCI layout and various OCILayoutTest cleanup

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/LayoutRef.java
- src/main/java/land/oras/ManifestDescriptor.java
- src/main/java/land/oras/OCI.java
- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/Ref.java
- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/OCILayoutTest.java
- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/RegistryWireMockTest.java
Push artifact to OCI layout
CI
> Push artifact to OCI layout

- src/main/java/land/oras/Descriptor.java
- src/main/java/land/oras/Index.java
Will be required to implement graph/copy
Index is now a descriptor
> Index is now a descriptor

- pom.xml
- src/main/java/land/oras/utils/DigestUtils.java
- src/main/java/land/oras/utils/SupportedAlgorithm.java
- src/test/java/land/oras/OCILayoutTest.java
- src/test/java/land/oras/utils/DigestUtilsTest.java
- src/test/java/land/oras/utils/SupportedAlgorithmTest.java
https://github.com/opencontainers/image-spec/issues/819
CI
> Support for blake3 (experimental)

- src/main/java/land/oras/Config.java
- src/main/java/land/oras/Descriptor.java
- src/main/java/land/oras/Index.java
- src/main/java/land/oras/Layer.java
- src/main/java/land/oras/Manifest.java
- src/main/java/land/oras/ManifestDescriptor.java
- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/IndexTest.java
- src/test/java/land/oras/RegistryTest.java
> Support for index subject

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/LayoutRef.java
- src/main/java/land/oras/Manifest.java
- src/main/java/land/oras/OCI.java
- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/Ref.java
- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/LayoutRefTest.java
- src/test/java/land/oras/ManifestTest.java
- src/test/java/land/oras/OCILayoutTest.java
Push attach artifact into OCI API
CI
> Push attach artifact into OCI API

- README.md
Update readme version for reproducible builds
None
> Update readme version for reproducible builds

- src/main/java/land/oras/utils/SupportedAlgorithm.java
- src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Signed-off-by: vaidikcode <vaidikbhardwaj00@gmail.com>
As decided, I plan to systematically divide PR #176 into three parts to ensure a smooth transition without breaking the build while still achieving the goal of adding `pushChunks`. For reference, I will keep PR #176 open.  
This PR introduces a getter method for retrieving the algorithm name. This is essential for `MessageDigest.getInstance()` and serves as a prerequisite for upcoming chunked upload support.  
This PR introduces the necessary HTTP components required for chunked uploads:  
- Adds constants for essential headers:  
- `Content-Range`  
- `Range`  
- `OCI-Chunk-Min-Length`  
- Enables support for the `PATCH` HTTP method in `OrasHttpClient`  
These updates lay the groundwork for efficient chunked blob uploads.  
This PR …
> add getter for algoritm name

- src/main/java/land/oras/OCI.java
- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/Registry.java
> Push up collect layer

- src/main/java/land/oras/utils/SupportedAlgorithm.java
- src/test/java/land/oras/LayerTest.java
- src/test/java/land/oras/utils/SupportedAlgorithmTest.java
Add support for sha384
Automated tests
> Add support for sha384

- pom.xml
Quick build profile 
mvn -Pquick-build install
> Quick build profile

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/ContainerRefTest.java
- src/test/java/land/oras/OCILayoutTest.java
- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/RegistryWireMockTest.java
Store registry URL into registry
This would alow better integration like https://github.com/quarkiverse/quarkus-oras
> Store registry URL into registry

- src/test/java/land/oras/RegistryWireMockTest.java
Signed -off-by : @kartiksharma-git [imailkartiksharma@gmail.com](https://github.com/oras-project/oras-java/pull/url)
Issue #23 
This PR adds and refines the test cases for the Registry Client to validate the ORAS Java SDK's functionality. Following are the new implemented test methods:
`shouldHandleRateLimitingResponse`: Tests handling of HTTP 429 Too Many Requests responses, ensuring proper OrasException with status code 429 is thrown.
`shouldHandleConcurrentBlobPushes`: Verifies concurrent registry.pushBlob calls for the same ContainerRef.
`shouldFollowRedirectOnBlobFetch`: Validates correct handling of HTTP 307 redirects during registry.getBlob, ensuring the client follows the redirect to fetch the blob.
- Tests run successfully in test environments.
- Tests pass in CI.
> add RateLimitng and Concurrency Tests in RegistryWireMockTest

- pom.xml
- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/utils/HttpClient.java
- src/test/java/land/oras/ContainerRefTest.java
- src/test/java/land/oras/DockerIoITCase.java
- src/test/java/land/oras/GitHubContainerRegistryITCase.java
Add support for integration tests and fix some issue with docker.io and GHCR
mvn -DskipUnitTests verify
> Add support for integration tests and fix some issue with docker.io and GHCR

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/auth/Scope.java
- src/main/java/land/oras/auth/ScopeUtils.java
- src/main/java/land/oras/utils/HttpClient.java
- src/test/java/land/oras/ContainerRefTest.java
- src/test/java/land/oras/RegistryWireMockTest.java
- src/test/java/land/oras/auth/AuthStoreAuthenticationProviderTest.java
- src/test/java/land/oras/auth/ScopeUtilsTest.java
- src/test/java/land/oras/auth/UsernamePasswordProviderTest.java
> Add utils for scopes management

- src/test/java/land/oras/JFrogArtifactoryITCase.java
- src/test/java/land/oras/QuayIoITCase.java
Add test for JFrog Artifactory and Quay.io
Just basic manifest pull
> Add test for JFrog Artifactory and Quay.io

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/OCI.java
- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/Repositories.java
- src/test/java/land/oras/ContainerRefTest.java
- src/test/java/land/oras/OCILayoutTest.java
- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/RegistryWireMockTest.java
List repositories
Fixes https://github.com/oras-project/oras-java/issues/274
> List repositories

- pom.xml
- src/main/java/land/oras/Annotations.java
- src/main/java/land/oras/ArtifactType.java
- src/main/java/land/oras/Config.java
- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/Describable.java
- src/main/java/land/oras/Descriptor.java
- src/main/java/land/oras/Index.java
- src/main/java/land/oras/Layer.java
- src/main/java/land/oras/LayoutRef.java
- src/main/java/land/oras/Manifest.java
- src/main/java/land/oras/ManifestDescriptor.java
- src/main/java/land/oras/OCI.java
- src/main/java/land/oras/OCILayout.java
- src/main/java/land/oras/OrasModel.java
- src/main/java/land/oras/Ref.java
- src/main/java/land/oras/Referrers.java
- src/main/java/land/oras/Subject.java
- src/main/java/land/oras/Tags.java
- src/main/java/land/oras/auth/HttpClient.java
- src/main/java/land/oras/exception/Error.java
- src/test/java/land/oras/ClassAnnotationsTest.java
Add OrasModel for better Quarkus reflective support
> Add OrasModel for better Quarkus reflective support

- .github/workflows/deploy-javadoc.yml
Fix javadoc build
mvn  generate-resources javadoc:javadoc
> Fix javadoc build

- src/main/java/land/oras/utils/ArchiveUtils.java
- src/test/java/land/oras/utils/ArchiveUtilsTest.java
Fix: https://github.com/oras-project/oras-java/issues/147
Check also created archive
```
tar xvsf /tmp/oras12228838129694979415.tar                                                                                                                                 [2
dir2/
dir2/file2
dir2/dir3/
dir2/dir3/file4
empty/
dir1/
dir1/file3
dir1/file1
```
> Fix tar/untar to never add current dir entry and avoid traversal attacks

- src/main/java/land/oras/utils/SupportedAlgorithm.java
- src/test/java/land/oras/utils/SupportedAlgorithmTest.java
> Add SHA1 utils

- src/main/generated/Versions.java
- src/main/java/land/oras/LayoutRef.java
- src/main/java/land/oras/Ref.java
- src/test/java/land/oras/OCILayoutTest.java
Convenience methods for layout ref
> Convenience methods for layout ref

- README.md
> Mention Quarkus ORAS

- src/main/java/land/oras/Registry.java
- src/test/java/land/oras/RegistryTest.java
Add more convenience methods on registry
> Add more convenience methods on registry

- src/test/java/land/oras/RegistryWireMockTest.java
Signed-off-by: @kartiksharma-git, [imailkartiksharma@gmail.com](url)
Issue #23 
`shouldHandleNetworkConnectivityLoss`: Simulates a network connectivity loss by having WireMock return a 503 Service Unavailable response. The test verifies that an OrasException with a "Response code: 503" message is thrown when the registry is queried.
`shouldHandleCorruptedResponse`: Simulates a corrupted blob response by returning a mismatched response body. The test checks that an OrasException is thrown with a "Digest mismatch" message when the blob's digest does not match the expected one.
- Tests successfully run in relevant environments.
- Tests pass in CI.
> add NetworkConnectivity and CorruptedResponses Tests using Wiremock

- .github/workflows/updatecli.yaml
Allow updatecli workflow to update actions
None
> Allow updatecli workflow to update actions

- README.md
Update reproducible badge
None
> Update reproducible badge

- src/test/java/land/oras/RegistryTest.java
- src/test/java/land/oras/utils/ZotUnsecureContainer.java
- updatecli/updatecli.d/zot.yaml
Test only.
Only add one test that verify the container is working
> Add zot unsecure container

- .github/workflows/build.yml
- pom.xml
Test build on Java 21 and Java 25
> Test build on Java 21 and Java 25

- src/main/java/land/oras/ContainerRef.java
- src/main/java/land/oras/Registry.java
- src/main/java/land/oras/auth/AuthStore.java
- src/main/java/land/oras/utils/Const.java
- src/test/java/land/oras/ContainerRefTest.java
- src/test/java/land/oras/RegistryTest.java
- src/test/resources/junit-platform.properties
> Add unqualified flag on container ref
